import { Product, Category, Offer, Banner, Review, RestaurantSettings } from '@/types/models';

export const INITIAL_SETTINGS: RestaurantSettings = {
  restaurantName: 'Sizzle & Slice',
  tagline: 'Artisanal Burgers, Wood-Fired Pizza & Gourmet Bites',
  phone: '+1 (555) 234-5678',
  whatsappNumber: '+15552345678', // e.g., international format without + or spaces
  email: 'orders@sizzlenslice.com',
  address: '742 Culinary Avenue, Gourmet District, NYC 10001',
  openingHours: 'Mon - Sun: 10:00 AM - 11:30 PM',
  deliveryFee: 3.99,
  freeDeliveryThreshold: 45.00,
  minOrderValue: 12.00,
  currencySymbol: '$',
  taxRate: 8.5,
  deliveryAreas: ['Downtown', 'Midtown', 'Gourmet District', 'Westside', 'Harbor Bay', 'East Heights'],
};

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'Burgers',
    slug: 'burgers',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80',
    description: 'Smash burgers, flame-grilled beef, & crispy chicken',
    itemCount: 8,
  },
  {
    id: 'cat-2',
    name: 'Pizza',
    slug: 'pizza',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=80',
    description: 'Wood-fired sourdough pizzas with imported mozzarella',
    itemCount: 6,
  },
  {
    id: 'cat-3',
    name: 'BBQ & Grills',
    slug: 'bbq',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=600&q=80',
    description: 'Slow-smoked ribs, tender brisket, and skewers',
    itemCount: 5,
  },
  {
    id: 'cat-4',
    name: 'Shawarma & Wraps',
    slug: 'shawarma',
    image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&w=600&q=80',
    description: 'Authentic spiced chicken & lamb shawarmas in warm pita',
    itemCount: 4,
  },
  {
    id: 'cat-5',
    name: 'Chinese & Asian',
    slug: 'chinese',
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80',
    description: 'Sizzling noodles, dim sum, and savory stir-fries',
    itemCount: 6,
  },
  {
    id: 'cat-6',
    name: 'Desserts & Ice Cream',
    slug: 'desserts',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80',
    description: 'Molten lava cakes, artisanal gelato, and waffles',
    itemCount: 7,
  },
  {
    id: 'cat-7',
    name: 'Beverages & Coffee',
    slug: 'drinks',
    image: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=600&q=80',
    description: 'Craft mocktails, iced lattes, fresh juices & boba tea',
    itemCount: 6,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'Truffle Double Bacon Cheeseburger',
    slug: 'truffle-double-bacon-cheeseburger',
    description: 'Double Angus beef patty, smoked applewood bacon, black truffle aioli, aged cheddar, caramelized onion jam on a toasted brioche bun.',
    category: 'burgers',
    price: 16.99,
    discountPercentage: 15,
    discountPrice: 14.44,
    currency: '$',
    rating: 4.9,
    totalReviews: 128,
    images: [
      'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=800&q=80',
    ],
    ingredients: ['Angus Beef', 'Applewood Bacon', 'Truffle Aioli', 'Aged Cheddar', 'Caramelized Onion', 'Brioche Bun'],
    preparationTime: '15-20 min',
    isAvailable: true,
    isPopular: true,
    isFeatured: true,
    isRecommended: true,
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-07-01T10:00:00Z',
  },
  {
    id: 'prod-2',
    name: 'Artisan Truffle & Mushroom Pizza',
    slug: 'artisan-truffle-mushroom-pizza',
    description: 'Wood-fired 72-hr fermented sourdough crust, wild mushrooms, fresh fior di latte, white truffle drizzle, & fresh basil.',
    category: 'pizza',
    price: 21.50,
    discountPercentage: 20,
    discountPrice: 17.20,
    currency: '$',
    rating: 4.95,
    totalReviews: 210,
    images: [
      'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?auto=format&fit=crop&w=800&q=80',
    ],
    ingredients: ['Sourdough', 'Wild Porcini Mushrooms', 'Fior di Latte', 'White Truffle Oil', 'Fresh Basil'],
    preparationTime: '18-25 min',
    isAvailable: true,
    isPopular: true,
    isFeatured: true,
    isRecommended: true,
    createdAt: '2026-01-12T10:00:00Z',
    updatedAt: '2026-07-05T10:00:00Z',
  },
  {
    id: 'prod-3',
    name: 'Smoked Texas BBQ Beef Ribs',
    slug: 'smoked-texas-bbq-beef-ribs',
    description: '12-hour hickory smoked full rack ribs with sweet bourbon glaze, served with garlic butter corn & coleslaw.',
    category: 'bbq',
    price: 26.99,
    discountPercentage: 0,
    discountPrice: 26.99,
    currency: '$',
    rating: 4.88,
    totalReviews: 94,
    images: [
      'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80',
    ],
    ingredients: ['Prime Beef Ribs', 'Bourbon BBQ Glaze', 'Garlic Butter Corn', 'House Coleslaw'],
    preparationTime: '20-30 min',
    isAvailable: true,
    isPopular: true,
    isFeatured: true,
    isRecommended: false,
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-07-02T10:00:00Z',
  },
  {
    id: 'prod-4',
    name: 'Gourmet Chicken Shawarma Roll',
    slug: 'gourmet-chicken-shawarma-roll',
    description: 'Marinated spit-roasted chicken thigh, garlic toum sauce, pickled cucumbers, crispy fries wrapped in warm lavash bread.',
    category: 'shawarma',
    price: 11.99,
    discountPercentage: 10,
    discountPrice: 10.79,
    currency: '$',
    rating: 4.82,
    totalReviews: 165,
    images: [
      'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&w=800&q=80',
    ],
    ingredients: ['Spiced Chicken Thigh', 'Garlic Toum', 'Pickled Turnip & Cucumber', 'Crispy Potato', 'Lavash Wrap'],
    preparationTime: '10-15 min',
    isAvailable: true,
    isPopular: true,
    isFeatured: false,
    isRecommended: true,
    createdAt: '2026-02-01T10:00:00Z',
    updatedAt: '2026-07-10T10:00:00Z',
  },
  {
    id: 'prod-5',
    name: 'Spicy Dragon Kung Pao Noodles',
    slug: 'spicy-dragon-kung-pao-noodles',
    description: 'Wok-tossed hand-pulled ramen noodles with chili oil, roasted peanuts, tender crispy chicken, scallions & Szechuan peppers.',
    category: 'chinese',
    price: 15.50,
    discountPercentage: 12,
    discountPrice: 13.64,
    currency: '$',
    rating: 4.79,
    totalReviews: 89,
    images: [
      'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=800&q=80',
    ],
    ingredients: ['Hand-Pulled Noodles', 'Crispy Chicken', 'Chili Crisp', 'Szechuan Peppercorns', 'Peanuts'],
    preparationTime: '15-20 min',
    isAvailable: true,
    isPopular: false,
    isFeatured: false,
    isRecommended: true,
    createdAt: '2026-02-10T10:00:00Z',
    updatedAt: '2026-07-11T10:00:00Z',
  },
  {
    id: 'prod-6',
    name: 'Belgian Dark Chocolate Molten Cake',
    slug: 'belgian-dark-chocolate-molten-cake',
    description: 'Warm chocolate cake with a oozing lava center made with 70% Valrhona dark chocolate, topped with vanilla bean ice cream.',
    category: 'desserts',
    price: 9.99,
    discountPercentage: 0,
    discountPrice: 9.99,
    currency: '$',
    rating: 4.98,
    totalReviews: 310,
    images: [
      'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=800&q=80',
    ],
    ingredients: ['Valrhona Dark Chocolate', 'Vanilla Gelato', 'Butter', 'Organic Eggs', 'Cocoa Dust'],
    preparationTime: '12 min',
    isAvailable: true,
    isPopular: true,
    isFeatured: true,
    isRecommended: true,
    createdAt: '2026-02-15T10:00:00Z',
    updatedAt: '2026-07-12T10:00:00Z',
  },
  {
    id: 'prod-7',
    name: 'Iced Caramel Cloud Cold Brew',
    slug: 'iced-caramel-cloud-cold-brew',
    description: 'Slow-steeped 20-hr cold brew espresso layered with Madagascar vanilla syrup, topped with salted caramel cold foam.',
    category: 'drinks',
    price: 6.49,
    discountPercentage: 0,
    discountPrice: 6.49,
    currency: '$',
    rating: 4.85,
    totalReviews: 142,
    images: [
      'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=800&q=80',
    ],
    ingredients: ['Arabica Cold Brew', 'Madagascar Vanilla', 'Sea Salt Caramel Foam', 'Ice'],
    preparationTime: '5 min',
    isAvailable: true,
    isPopular: true,
    isFeatured: false,
    isRecommended: false,
    createdAt: '2026-03-01T10:00:00Z',
    updatedAt: '2026-07-15T10:00:00Z',
  },
];

export const INITIAL_OFFERS: Offer[] = [
  {
    id: 'offer-1',
    title: 'WELCOME20 - 20% OFF Your First Feast',
    code: 'WELCOME20',
    description: 'Get 20% discount on all orders over $25. Valid for new visitors!',
    discountPercentage: 20,
    maxDiscount: 15,
    minOrderAmount: 25,
    validUntil: '2026-12-31',
    bannerUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80',
    isAvailable: true,
  },
  {
    id: 'offer-2',
    title: 'FREE DELIVERY WEEKEND',
    code: 'FREEDEL',
    description: 'Enjoy zero delivery fees on orders above $30 anywhere in town.',
    discountPercentage: 100,
    maxDiscount: 5,
    minOrderAmount: 30,
    validUntil: '2026-09-30',
    bannerUrl: 'https://images.unsplash.com/photo-1526367790999-0150786686a2?auto=format&fit=crop&w=1200&q=80',
    isAvailable: true,
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    productId: 'prod-1',
    productName: 'Truffle Double Bacon Cheeseburger',
    userName: 'Alexander Wright',
    userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    rating: 5,
    comment: 'Hands down the best burger in the city! The truffle aioli combined with the caramelized onion jam is perfection. Arrived piping hot via WhatsApp order!',
    isApproved: true,
    createdAt: '2026-07-18T14:30:00Z',
  },
  {
    id: 'rev-2',
    productId: 'prod-2',
    productName: 'Artisan Truffle & Mushroom Pizza',
    userName: 'Sophia Martinez',
    userAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80',
    rating: 5,
    comment: 'The crust on this pizza is magical. Crispy on the outside, light and chewy inside. Super quick order confirmation on WhatsApp!',
    isApproved: true,
    createdAt: '2026-07-20T19:15:00Z',
  },
];
